Capstone Project
odaialazzeh/Web-Development-course pull request #1
Opened 2022-10-26 16:09 UTC by odaialazzeh

## HTML pages:
- [ ] I have created two pages for the project, the home and the about page. 
- [ ] Create an images folder with the necessary images for the design.

## CSS file:

- [ ] I have created style.css which contains the style of both pages and also added the styles for desktop and mobile versions.

## JavaScript file:

- [ ] I have created a javascript file with codes to open and close the mobile menu and dynamically implement the speaker's section when the pages to load. 

## Link to the video:

- [ ]  This is the link to the recorded video 
https://www.loom.com/share/d32fce7cca744904a5cb58488fe5e275

2022-10-26 16:32 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @odaialazzeh 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media0.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Meaningful commit messages ✔️ 
* Professional README file ✔️
* The website is looking awesome 💯 Keep rocking 🚀 
* Presentation video was very informational and professional ✨ 

## Required Changes:
_Kindly check the comments below_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 16:32 UTC, ha-manel commented on README.md
> +https://odaialazzeh.github.io/capstone1-project/
- [ ] Kindly add `/home.html` to this link so it takes us to the home page of the website and not the README of the repo 👍

2022-10-26 16:32 UTC, ha-manel commented on README.md
> +- [Stackoverflow ](https://stackoverflow.com)
- [ ] Kindly add credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/) (and as indicated in the project requirements) 👍

2022-10-26 16:32 UTC, ha-manel commented on about.html
> +        </div>
- [ ] Kindly try to follow the design guidelines as much as possible. For the partners section (in the about page), it's hidden in the desktop version and it's visible in the mobile version.

## Your design:
![image](https://user-images.githubusercontent.com/50721479/198081671-604ed661-62f8-496c-b281-378b3d9059a3.png)

## Design guidelines: 
![image](https://user-images.githubusercontent.com/50721479/198081584-dc6b061f-70d9-44ca-aa04-a542aaee4a10.png)

2022-10-26 16:32 UTC, ha-manel commented on about.html
> +            </div>
- [ ] For the footer part of the about page, kindly make it dark for desktop version and light in the mobile version, to match the design guidelines 💯 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/198081979-e58138b7-3ffa-42ad-8f06-083c2c04959b.png)

## Design guidelines:
![image](https://user-images.githubusercontent.com/50721479/198082016-b8642528-05fe-4887-af37-ebe1191e2ce7.png)

2022-10-26 16:32 UTC, ha-manel commented on home.html
> +             <p id="p-main">Web development course using HTML, CSS, and JavaScript</p>
- [ ] Kindly make this element an `h1` instead of `p` since this is the main header of the page 👍

2022-10-26 16:32 UTC, ha-manel commented on about.html
> +             <p>Web development course using HTML, CSS, and JavaScript</p>
- [ ]  Kindly make this element an `h1` instead of `p` since this is the main header of the page 👍

2022-10-27 09:50 UTC, nedjwab approved these changes
# 🟢 Project Approved! 🏆

## Hi @odaialazzeh  👋

Your project is complete! ✔️ 🏁

Your code was very professional 💯

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉

 
## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors
- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 10:28 UTC, merged